### ISSUE TITLE
Ogre fails to compile on OSX 10.9, Xcode 5.0.1

### ISSUE THREAD

**Issue by Lenskiy** [osrf/homebrew-simulation#2]
I get compilation errors compiling ogre on mavericks,

```
/tmp/ogre-w8hs/ogre_src_v1-7-4/RenderSystems/GL/src/OSX/OgreOSXCocoaWindow.mm:103:43: error: no matching constructor for initialization of 'NameValuePairList::const_iterator'
      (aka '__map_const_iterator<typename __base::const_iterator>')
...
/tmp/ogre-w8hs/ogre_src_v1-7-4/RenderSystems/GL/src/OSX/OgreOSXCocoaWindow.mm:223:51: error: no matching constructor for initialization of 'NameValuePairList::const_iterator'
      (aka '__map_const_iterator<typename __base::const_iterator>')
                NameValuePairList::const_iterator param_useNSView_pair(NULL);
...
/tmp/ogre-w8hs/ogre_src_v1-7-4/RenderSystems/GL/src/OSX/OgreOSXGLSupport.mm:314:43: error: no matching constructor for initialization of 'NameValuePairList::const_iterator' (aka
      '__map_const_iterator<typename __base::const_iterator>')
        NameValuePairList::const_iterator opt(NULL);
                                          ^   ~~~~
```
